const CASES=[
{id:"c1",name:"STARTER",price:100,art:"🗡️",items:[["Rust Knife","common",35,"🔪"],["Glock Lime","common",90,"🔫"],["USP Carbon","rare",180,"🔫"],["Shadow Knife","epic",360,"🗡️"],["Butterfly Gold","legendary",850,"🦋"]]},
{id:"c2",name:"NEON",price:200,art:"🔫",items:[["P250 Pulse","common",70,"🔫"],["MP7 Neon","common",140,"🔫"],["M4A1 Wave","rare",280,"🔫"],["Karambit Blue","epic",620,"🔪"],["Butterfly Cyber","legendary",1400,"🦋"]]},
{id:"c3",name:"GOLD",price:400,art:"👑",items:[["Five-SeveN Gold","common",120,"🔫"],["AK Gold Line","rare",330,"🔫"],["M4 Gold","rare",520,"🔫"],["Deagle Royal","epic",1000,"🔫"],["Karambit Gold","legendary",2200,"🔪"]]},
{id:"c4",name:"DRAGON",price:500,art:"🐉",items:[["Tec-9 Flame","common",90,"🔫"],["AWP Dragon","rare",450,"🎯"],["AK Inferno","epic",900,"🔫"],["Talon Crimson","epic",1500,"🔪"],["Dragon Karambit","legendary",3500,"🐉"]]}
];
const weights={common:58,rare:25,epic:14,legendary:3};
let balance=Number(localStorage.cb_balance??5000);let inv=JSON.parse(localStorage.cb_inv??"[]");if(!Array.isArray(inv))inv=[];
let filter="all", busy=false, fromId="", toId="";
const $=id=>document.getElementById(id), money=n=>Math.round(n).toLocaleString("ru-RU");
function save(){localStorage.cb_balance=balance;localStorage.cb_inv=JSON.stringify(inv);$("balance").textContent=money(balance);$("count").textContent=inv.length}
function item(name,rarity,value,emoji){return{id:Date.now()+"_"+Math.random(),name,rarity,value,emoji}}
function drop(c){let pool=[];for(const x of c.items){for(let i=0;i<(weights[x[1]]||1);i++)pool.push(x)}let x=pool[Math.floor(Math.random()*pool.length)];return item(...x)}
function toast(t){let e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function renderCases(){$("caseGrid").innerHTML=CASES.map(c=>`<article class="case"><span class="tag">${c.name}</span><div class="art">${c.art}</div><h3>${c.name}<span class="price">◆ ${c.price}</span></h3><p>Стоимость кейса · риск / награда</p><button class="open" onclick="openCase('${c.id}')">ОТКРЫТЬ</button></article>`).join("")}
function renderInv(){let a=filter==="all"?inv:inv.filter(x=>x.rarity===filter);$("count").textContent=inv.length;if(!a.length){$("inv").innerHTML='<div style="grid-column:1/-1;text-align:center;padding:50px;color:#666a83">Инвентарь пуст</div>';return}$("inv").innerHTML=a.slice().reverse().map(x=>`<article class="item"><div class="emoji">${x.emoji}</div><div class="rarity">${x.rarity}</div><h4>${x.name}</h4><div class="value">◆ ${money(x.value)}</div><button class="sell" onclick="sell('${x.id}')">ПРОДАТЬ · ◆ ${money(x.value)}</button></article>`).join("")}
function openCase(id){if(busy)return;let c=CASES.find(x=>x.id===id);if(balance<c.price){toast("Не хватает ◆ "+c.price);return}balance-=c.price;let won=drop(c);busy=true;save();$("modal").classList.remove("hidden");$("modalTitle").textContent="ОТКРЫВАЕМ "+c.name;$("modalText").textContent="Крутим барабан...";$("modalBtn").classList.add("hidden");setTimeout(()=>{inv.push(won);busy=false;save();renderInv();$("modalTitle").textContent="ДРОП!";$("modalText").innerHTML=`${won.emoji} <b>${won.name}</b><br>Стоимость: ◆ ${money(won.value)}`;$("modalBtn").textContent="ЗАБРАТЬ";$("modalBtn").classList.remove("hidden")},2200)}
function sell(id){let i=inv.findIndex(x=>String(x.id)===String(id));if(i<0)return;let x=inv[i];inv.splice(i,1);balance+=Number(x.value);save();renderInv();toast("Продано за ◆ "+money(x.value))}
function fillSelects(){let from=$("from"),to=$("to");from.innerHTML='<option value="">Выбери предмет</option>'+inv.map(x=>`<option value="${x.id}">${x.name} — ◆ ${money(x.value)}</option>`).join("");let f=inv.find(x=>x.id===fromId);to.innerHTML='<option value="">Выбери цель дороже</option>'+inv.filter(x=>f&&x.value>f.value).sort((a,b)=>a.value-b.value).map(x=>`<option value="${x.id}">${x.name} — ◆ ${money(x.value)}</option>`).join("");from.value=fromId;to.value=toId}
function card(el,x,empty){el.innerHTML=x?`<div><div class="big">${x.emoji}</div><b>${x.name}</b><small>◆ ${money(x.value)}</small></div>`:empty}
function updateUpgrade(){let f=inv.find(x=>x.id===$("from").value),t=inv.find(x=>x.id===$("to").value);fromId=f?.id||"";toId=t?.id||"";card($("fromCard"),f,"Выбери предмет");card($("toCard"),t,"Выбери скин дороже");if(f&&t&&t.value>f.value){let ch=Math.min(95,Math.max(1,f.value/t.value*100));$("chance").textContent=ch.toFixed(0)+"%";$("chanceBar").style.width=ch+"%";$("upgradeBtn").disabled=false}else{$("chance").textContent="—";$("chanceBar").style.width="0";$("upgradeBtn").disabled=true}}
function upgrade(){if(busy)return;let f=inv.find(x=>x.id===$("from").value),t=inv.find(x=>x.id===$("to").value);if(!f||!t||t.value<=f.value)return;let ch=Math.min(95,Math.max(1,f.value/t.value*100));let ok=Math.random()*100<ch;busy=true;$("modal").classList.remove("hidden");$("modalTitle").textContent="УЛУЧШАЕМ...";$("modalText").textContent=`Шанс ${ch.toFixed(0)}% · вращаем...`;$("modalBtn").classList.add("hidden");setTimeout(()=>{let fi=inv.findIndex(x=>x.id===f.id);if(fi>=0)inv.splice(fi,1);if(ok){let ti=inv.findIndex(x=>x.id===t.id);if(ti>=0)inv.splice(ti,1);inv.push(item(t.name,t.rarity,t.value,t.emoji));$("modalTitle").textContent="УСПЕХ!";$("modalText").innerHTML=`Ты получил <b>${t.name}</b> · ◆ ${money(t.value)}`}else{$("modalTitle").textContent="НЕ ПОВЕЗЛО";$("modalText").textContent=`Шанс был ${ch.toFixed(0)}%. Скин сгорел.`}busy=false;save();renderInv();fillSelects();updateUpgrade();$("modalBtn").textContent="ЗАКРЫТЬ";$("modalBtn").classList.remove("hidden")},2300)}
$("from").onchange=()=>{toId="";fillSelects();updateUpgrade()};$("to").onchange=updateUpgrade;$("upgradeBtn").onclick=upgrade;$("modalBtn").onclick=()=>$("modal").classList.add("hidden");
$("filters").onclick=e=>{let b=e.target.closest("button");if(!b)return;filter=b.dataset.f;document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("on"));b.classList.add("on");renderInv()};
$("reset").onclick=()=>{if(confirm("Сбросить баланс и инвентарь?")){balance=5000;inv=[];save();renderInv();fillSelects();updateUpgrade()}};
document.querySelector("nav").onclick=e=>{let b=e.target.closest("button[data-page]");if(!b)return;document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(b.dataset.page).classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");if(b.dataset.page==="upgrade"){fillSelects();updateUpgrade()}};
renderCases();save();renderInv();fillSelects();updateUpgrade();